import { HttpException } from '@nestjs/common';

export const ErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  SCHEDULE_NOT_APPROVED: 'SCHEDULE_NOT_APPROVED',
  SCHEDULE_ALREADY_REGISTERED: 'SCHEDULE_ALREADY_REGISTERED',
  SCHEDULE_NOT_EDITABLE: 'SCHEDULE_NOT_EDITABLE',
  APPOINTMENT_SLOT_ALREADY_BOOKED: 'APPOINTMENT_SLOT_ALREADY_BOOKED',
  APPOINTMENT_SLOT_UNAVAILABLE: 'APPOINTMENT_SLOT_UNAVAILABLE',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PATIENT_PROFILE_CREATE_FAILED: 'PATIENT_PROFILE_CREATE_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorBody {
  statusCode: number;
  code: string;
  message: string;
}

export class AppException extends HttpException {
  constructor(statusCode: number, code: string, message: string) {
    super({ statusCode, code, message } satisfies ApiErrorBody, statusCode);
  }
}
